require("user.options")
require("user.autocmd")
require("user.keymaps")
require("user.plugins")
require("user.tokyonight")
require("user.colorscheme")
require("user.cmp")
require("user.snippets")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.surround")
require("user.hop")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
-- require("user.bufferline")
require("user.lualine")
require("user.neoscroll")
require("user.gomove")
require("user.neoclip")
require("user.sessions")
require("user.workspaces")
require("user.alpha")
require("user.indentline")
require("user.harpoon")
require("user.nvim-tree")
-- require("user.lir")
require("user.toggleterm")
require("user.colorizer")
vim.cmd("source $LOCALAPPDATA/nvim/lua/user/wiki.vim")
vim.cmd("source $LOCALAPPDATA/nvim/lua/user/emmet.vim")
vim.cmd("source $LOCALAPPDATA/nvim/lua/user/bullets.vim")
