inherits = "tokyonight"

# remove italic
comment = { fg = "comment" }
function = { fg = "blue" }
keyword = { fg = "purple" }
"keyword.control.return" = { fg = "purple" }
"variable.parameter" = { fg = "yellow" }

# colors from poimadres
punctuation = "#a6accd"
"punctuation.bracket" = "desaturatedBlue"
operator = "desaturatedBlue"

"ui.virtual" = "comment"
"ui.cursor.primary.normal" = { fg = "bg", bg = "lavender" }
"ui.cursor.normal" = { fg = "bg", bg = "blue" }
"ui.cursor.insert" = { fg = "bg", bg = "light-green" }
"ui.cursor.select" = { fg = "bg", bg = "magenta" }

"ui.text" = {}
"ui.picker.header.column.active" = { fg = "blue", modifiers = ["bold"] }

[palette]
bg = "#0c0d11"
lavender = "#b4befe"
desaturatedBlue = "#91B4D5"
