# Control Backspace, delete 1 word at a time
- key:
    Backspace:
  modifiers:
    CTRL:
  binding:
    Kill:
      BackwardWord:
        repeat: 1
        word: Big

# Undo
- key:
    Char: "_"
  modifiers:
    CTRL_SHIFT:
  binding:
    Undo: 1
