gui:
  enlargedSideViewLocation: 'top' # one of 'left' | 'top'
  nerdFontsVersion: 3 # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  theme:
    selectedLineBgColor:
      - '#292e42' # set to `default` to have no background colour
  statusPanelView: allBranchesLog
  useHunkModeInStagingView: true
git:
  allBranchesLogCmds:
    - git log --color=always --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset" --abbrev-commit --date=relative
