theme = "my_tokyonight"

[editor]
scrolloff = 5
line-number = "relative"
auto-format = false
idle-timeout = 50
completion-timeout = 50
cursorline = true
color-modes = true
completion-trigger-len = 1
shell = ["nu", "--no-std-lib", "--no-config-file", "--no-newline", "--stdin", "-c"]
bufferline = "multiple"
default-line-ending = "lf"
insert-final-newline = false
popup-border = "all"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
# character = "╎"
skip-levels = 1

[editor.lsp]
display-messages = true

[editor.gutters.line-numbers]
min-width = 2

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator", "diagnostics"]
center = []
right = [
  "version-control",
  "register",
  "position",
  "position-percentage",
  "spacer",
  "selections",
  "file-encoding",
  "file-line-ending",
]

[editor.smart-tab]
enable = false

[editor.file-picker]
hidden = false

[keys.normal]
"\\" = { c = ":config-open", r = ":config-reload" }
m = { "'" = "save_selection" }
# esc = ["collapse_selection", "keep_primary_selection"]
# "%" = ["save_selection", "select_all"]
C-q = ":quit!"
minus = "trim_selections"
A-d = ":bc"
A-F = ":format"
A-s = ":update"
A-w = "goto_last_accessed_file"
C-A-S-F6 = "jump_forward"
C-i = "jump_forward"
C-o = "jump_backward"
A-n = "repeat_last_motion"
# C-c = "no_op" # turn off the default comment functionality
C-u = ["page_cursor_half_up", "align_view_center"]
C-d = ["page_cursor_half_down", "align_view_center"]
C-y = "scroll_up"
C-e = "scroll_down"
C-k = [
  "goto_window_top",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
]
C-j = [
  "goto_window_bottom",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
]
C-ret = [
  "goto_window_bottom",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
]

# # move line down
# C-n = ["extend_to_line_bounds", "delete_selection", "paste_after", "flip_selections"]
# # move line up
# C-p = [
#   "extend_to_line_bounds",
#   "delete_selection",
#   "move_line_up",
#   "paste_before",
#   "flip_selections",
# ]

C-n = [
  "move_prev_word_end",
  "goto_next_paragraph",
  "collapse_selection",
  "move_visual_line_down",
  "insert_at_line_end",
  "normal_mode",
  "insert_at_line_start",
  "normal_mode",
  "goto_next_paragraph",
  "trim_selections",
]
C-p = [
  "move_next_word_start",
  "goto_prev_paragraph",
  "move_visual_line_up",
  "goto_prev_paragraph",
  "trim_selections",
]

# A-x = ["extend_to_line_bounds", "trim_selections"]
# A-c = ["extend_to_line_bounds", "trim_selections", "change_selection"]
# a = ["ensure_selections_forward", "collapse_selection", "move_char_right", "insert_mode"]

# Muscle memory
D = ["extend_to_line_end", "delete_selection"]
Z = { Z = ":wq", Q = ":q!" }
G = "goto_last_line"
# C = ["collapse_selection", "extend_to_line_end", "change_selection"]
V = ["select_mode", "extend_to_line_bounds"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

H = "goto_window_top"
L = "goto_window_bottom"
M = "goto_window_center"

# from: https://github.com/helix-editor/helix/pull/9080#issuecomment-2008964831
# The bonus is that `X` pairs ergonomically with `C` and `(` `)`.
J = "select_line_below"
K = "select_line_above"
X = "remove_primary_selection"
x = "keep_selections"
A-x = "remove_selections"
"'" = "flip_selections"
A-A = "select_all_siblings"

# X = "extend_line_above"
# B = "extend_prev_word_start"
# W = "extend_next_word_start"
# H = "extend_char_left"
# L = "extend_char_right"

g.S = "extend_to_first_nonwhitespace"
g.L = "extend_to_line_end"
g.H = "extend_to_line_start"

[keys.normal.space]
l = "join_selections"
L = "join_selections_space"
F = "file_picker_in_current_buffer_directory"

[keys.select.space]
l = "join_selections"
L = "join_selections_space"

[keys.normal.space.u]
f = ":toggle auto-format"
g = ":toggle indent-guides.render"
i = ":toggle lsp.display-inlay-hints"
w = ":toggle soft-wrap.enable"
l = ":toggle whitespace.render all none"
r = ":toggle line-number relative absolute"
z = ":toggle gutters.line-numbers.min-width 30 2"  # limited zen mode
d = ":toggle end-of-line-diagnostics hint disable"

[keys.insert]
C-y = "scroll_up"
C-e = "scroll_down"
C-right = ["move_next_word_start", "move_char_right"]
C-left = ["move_prev_word_end", "collapse_selection"]
C-space = "completion"
A-C-S-F5 = "completion"
C-backspace = "delete_word_backward"
A-C-S-F6 = "jump_forward"
C-i = "jump_forward"
C-o = "jump_backward"
A-s = ["normal_mode", ":update"]
A-w = "goto_last_accessed_file"
A-e = "move_parent_node_end"
A-b = "move_parent_node_start"

# C-k = "goto_prev_tabstop"
# C-j = "goto_next_tabstop"
# C-ret = "goto_next_tabstop"

[keys.select]
C-y = "scroll_up"
C-e = "scroll_down"
C-k = [
  "goto_window_top",
  "extend_line_up",
  "extend_line_up",
  "extend_line_up",
  "extend_line_up",
  "extend_line_up",
]
C-j = [
  "goto_window_bottom",
  "extend_line_down",
  "extend_line_down",
  "extend_line_down",
  "extend_line_down",
  "extend_line_down",
]
C-ret = [
  "goto_window_bottom",
  "extend_line_down",
  "extend_line_down",
  "extend_line_down",
  "extend_line_down",
  "extend_line_down",
]
minus = "trim_selections"
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
G = "goto_file_end"
A-n = "repeat_last_motion"

H = "goto_window_top"
L = "goto_window_bottom"
M = "goto_window_center"

J = "select_line_below"
K = "select_line_above"
X = "remove_primary_selection"
x = "keep_selections"
A-x = "remove_selections"
"'" = "flip_selections"
A-A = "select_all_siblings"
