[[language]]
name = "html"
language-servers = [
  { name = 'emmet-lsp' },
  { name = 'vscode-html-language-server', except-features = ['format'] },
]
formatter = { command = "prettierd", args = ["--stdin-filepath", "a.html"] }
auto-format = false

[[language]]
name = "css"
language-servers = [{ name = 'vscode-css-language-server', except-features = ['format'] }]
formatter = { command = "prettierd", args = ["--stdin-filepath", "a.css"] }

[[language]]
name = "markdown"
formatter = { command = "prettierd", args = ["--stdin-filepath", "a.md"] }

[[language]]
name = "json"
file-types = ["none"]
language-servers = [
  { name = 'biome' },
  { name = 'vscode-json-language-server', except-features = ['format'] },
]

[[language]]
name = "jsonc"
file-types = [
  "json",
  "arb",
  "ipynb",
  "geojson",
  "gltf",
  "webmanifest",
  { glob = "flake.lock" },
  { glob = ".babelrc" },
  { glob = ".bowerrc" },
  { glob = ".jscrc" },
  "js.map",
  "ts.map",
  "css.map",
  { glob = ".jslintrc" },
  "jsonl",
  "jsonld",
  { glob = ".vuerc" },
  { glob = "composer.lock" },
  { glob = ".watchmanconfig" },
  "avsc",
  { glob = ".prettierrc" },
]
language-servers = [
  { name = 'biome' },
  { name = 'vscode-json-language-server', except-features = ['format'] },
]

# fix taplo: https://github.com/tamasfe/taplo/issues/580#issuecomment-2004174721
[[language]]
name = 'toml'
roots = ["."]

[language-server.taplo]
required-root-patterns = [".taplo.toml"]

[[language]]
name = "javascript"
language-servers = [
  'scls',
  { name = 'biome' },
  { name = 'typescript-language-server', except-features = ['format'] },
]
# auto-format = true

[[language]]
name = "typescript"
language-servers = [
  'scls',
  { name = 'biome' },
  { name = 'typescript-language-server', except-features = ['format'] },
]
# auto-format = true

[[language]]
name = "jsx"
language-servers = [
  { name = 'biome' },
  { name = 'typescript-language-server', except-features = ['format'] },
]
# auto-format = true

[[language]]
name = "tsx"
language-servers = [
  { name = 'biome' },
  { name = 'typescript-language-server', except-features = ['format'] },
]
# auto-format = true

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 20            # set max completion results len for each group: words, snippets, unicode-input
snippets_first = false               # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_words = false                # enable completion by word
feature_snippets = true              # enable snippets
feature_unicode_input = true         # enable "unicode input"
feature_paths = false                # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.rust-analyzer]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]
required-root-patterns = ["biome.json", "biome.jsonc"]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]
required-root-patterns = [".eslintrc*", "eslint.config.*"]

[language-server.eslint.config]
# format = true
nodePath = ""
onIgnoredFiles = "off"
# packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { mode = "all" }
experimental = {}
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = ["tsconfig.json", "tsconfig.*.json"]
url = "https://json.schemastore.org/tsconfig.json"

[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = ["package.json"]
url = "https://json.schemastore.org/package.json"
