[language-server.rust-analyzer]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]

[[language]]
name = "javascript"
language-servers = [{ name = "typescript-language-server" }, "eslint"]

[[language]]
name = "typescript"
language-servers = [{ name = "typescript-language-server" }, "eslint"]

[[language]]
name = "jsx"
language-servers = [{ name = "typescript-language-server" }, "eslint"]

[[language]]
name = "tsx"
language-servers = [{ name = "typescript-language-server" }, "eslint"]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
# format = true
nodePath = ""
onIgnoredFiles = "off"
# packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { mode = "all" }
experimental = { }
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }
